### ISSUE TITLE
CSS files are missed if they are not in DOM

### ISSUE THREAD

**Issue by ksenia-loseva** [percy/percy-java-selenium#41]
Percy currently saves DOM, then uploads it to the server and processes. However, this approach doesn't work if styles are not in DOM but are separate files. In this case, the page is not rendered correctly in Percy.

**Comment by Robdel12** [comment]
Hey @ksenia-loseva sorry for the late reply on this! I unfollowed this repo somehow 🤔 

If this is still an issue, could you reach out via our intercom support? Percy captures CSS in various ways (inline in the DOM, in-memory CSSOM styles, and linked files). It sounds like either the requests to those CSS files are failing or they might be `blob:` assets (which can't be captured).
