### ISSUE TITLE
Version 0.1.0 is Giving the following Error: WARNING: Something went wrong trying to load {}. Snapshotting will not work.

### ISSUE THREAD

**Issue by borgandrea** [percy/percy-java-selenium#42]
When using the following Maven Dependency Version: 0.1.0 

I get the following Warnings: 

WARNING: Something went wrong trying to load {}. Snapshotting will not work.
Oct 18, 2019 4:42:08 PM io.percy.selenium.Percy snapshot
WARNING: percy-agent.js is not available. Snapshotting is disabled.

[percy] stopping percy...
[percy] waiting for 0 snapshots to complete...
[percy] done.

Using maven Dependency version: 0.0.3 everything works fine. 

Node version: v8.11.1
java version "1.8.0_172"
Apache Maven 3.5.3

**Comment by KengoTODA** [comment]
I faced the same issue, and its reason is clear; the `.jar` file doesn't contain `percy-agent.js`.

I guess the build script change in 63472732489178fbf41b2f87d70a9b86a30a990b caused this problem. @Robdel12

**Comment by Robdel12** [comment]
Hey @KengoTODA that looks like its most likely that issue! I have a PR up (#44) to fix that -- we shouldn't be bundling that library with the build. It should be requested 😊

I do see your PR! That is greatly appreciated. Once #44 ships, could you rebase your changes?

**Comment by KengoTODA** [comment]
#44 removed the logging operation, then this issue can be closed.
I will rebase my PR to fix resource leak problems only.

**Comment by Robdel12** [comment]
I believe this has been fixed in v0.1.1 (v0.1.2 is the latest at the time of this comment though)
