### ISSUE TITLE
Unable to take a screenshot - too much JS maybe???

### ISSUE THREAD

**Issue by taniapil** [percy/percy-java-selenium#60]
I'm trying to use percy to take a screenshot of our web page and I get 413 error code. You can see the full response in the following screenshot.
![image](https://user-images.githubusercontent.com/14974400/83873491-981af000-a73c-11ea-96f6-260974be6a12.png)

I use Java and this is the line I have added to my test to take the screenshot
`percy.snapshot("Test screenshot", Arrays.asList(1920), 2000, true)`

I came across [this issue ](https://github.com/percy/percy-cypress/issues/105#issuecomment-492724111) and I realised that we may have too much JavaScript as well. 
Our bundle was too big (around 7MB) and we managed to limit it to around 1.2MB, but I still get the same error.
Can you guide me on how to solve this issue? What's the limit (in KB/MB) for JS?

**Comment by wwilsman** [comment]
Hi @taniapil!

Does the error go away when you leave JavaScript disabled for the snapshot? If so, then it could be a different JS bundle than one you're expecting. If it doesn't go away then it's likely some other asset is too large, such as an image.

If you add the environment variable `LOG_LEVEL=debug`, that will print out more detailed debug logs. That will help determine which request might be causing this error.

**Comment by taniapil** [comment]
Hi @wwilsman!

Sorry for the late reply but I didn't have the time to try this until now.

It seems that the environment variable `LOG_LEVEL=debug` did the trick either the `enableJavascript` param is used or not.
Without this env var it still fails with the error I mentioned in my first comment.

**Comment by wwilsman** [comment]
Very interesting. That environment variable only controls what get's logged to the console output. It shouldn't have any bearing on file sizes 🤔
