### ISSUE TITLE
Missing a 's' for the placeholder in String.format

### ISSUE THREAD

**Issue by hstonec** [percy/percy-java-selenium#7]
Hi, I just happened to notice that there seems missing a 's' for placeholder in String.format. If I am not wrong, it should be `return String.format("selenium-java; unknownDriver; %s", innerDriver.getClass().getName());`

https://github.com/percy/percy-java-selenium/blob/ee0b8a378749019276596269f1208c0200b4af03/src/main/java/io/percy/selenium/Environment.java#L84

**Comment by anaulin** [comment]
You're absolutely right, @hstonec . Fix coming soon.
